version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: roomies-postgres-dev
    environment:
      POSTGRES_USER: roomies_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: roomies_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - roomies-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roomies_user -d roomies_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: roomies-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - roomies-network
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    sysctls:
      - net.core.somaxconn=1024

  # Redis Commander (Web UI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: roomies-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8081:8081"
    networks:
      - roomies-network
    depends_on:
      - redis
    restart: unless-stopped

  # Roomies Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: roomies-backend-dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: roomies_user
      DB_PASSWORD: secure_password
      DB_DATABASE: roomies_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_KEY_PREFIX: roomies:dev:
      JWT_SECRET: dev-jwt-secret-change-in-production
      CLIENT_URL: http://localhost:3000
      LOG_LEVEL: debug
      ENABLE_DEBUG_ENDPOINTS: true
      ENABLE_SAMPLE_DATA: true
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - roomies-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: roomies-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@roomies.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - roomies-network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    name: roomies-postgres-data
  redis_data:
    driver: local  
    name: roomies-redis-data
  pgadmin_data:
    driver: local
    name: roomies-pgadmin-data

networks:
  roomies-network:
    driver: bridge
    name: roomies-dev-network
    ipam:
      config:
        - subnet: 172.20.0.0/16
