name: Realtime E2E

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  realtime-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    defaults:
      run:
        working-directory: roomies-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci --no-optional

      - name: Build backend
        run: npm run build

      - name: Start server
        run: node dist/server.js &

      - name: Wait for server to be ready
        run: |
          for i in {1..20}; do
            if curl -sSf http://localhost:3000/health >/dev/null; then
              echo "Server is up"; exit 0; fi; sleep 1; done; exit 1

      - name: Run realtime E2E test
        run: npm run test:realtime

      - name: Upload server logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: backend-logs
          path: roomies-backend/logs


